In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(616)

inventory = rng.integers(0,100,10)
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [4]:
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33], dtype=int64)

In [6]:
inventory + 5

array([44, 44, 98, 91, 53, 51, 53, 35, 16, 62], dtype=int64)

In [5]:
inventory / 2

array([19.5, 19.5, 46.5, 43. , 24. , 23. , 24. , 15. ,  5.5, 28.5])

In [7]:
(inventory / 2).dtype

dtype('float64')

In [8]:
price = (rng.random(11) * 10)

price

array([0.88884683, 8.81943469, 7.3228387 , 7.32151822, 5.62333941,
       3.39669286, 0.62511   , 3.57068164, 2.02503188, 4.305179  ,
       1.03316301])

In [14]:
price = (rng.random(10) * 10).round(2)

price

array([8.04, 5.59, 5.5 , 9.31, 1.17, 6.95, 4.72, 5.31, 2.95, 3.07])

In [15]:
price * inventory

array([313.56, 218.01, 511.5 , 800.66,  56.16, 319.7 , 226.56, 159.3 ,
        32.45, 174.99])

In [16]:
(price * inventory).sum()

2812.8899999999994

In [17]:
inventory_list = list(inventory)

In [18]:
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [19]:
inventory_list

[39, 39, 93, 86, 48, 46, 48, 30, 11, 57]

In [21]:
inventory + 2

array([41, 41, 95, 88, 50, 48, 50, 32, 13, 59], dtype=int64)

In [20]:
new_inventory = []

for x in inventory_list:
    new_inventory.append(x + 2)

new_inventory

[41, 41, 95, 88, 50, 48, 50, 32, 13, 59]

In [22]:
[x + 2 for x in inventory_list]

[41, 41, 95, 88, 50, 48, 50, 32, 13, 59]

In [23]:
[x * 2 for x , y in zip(inventory_list, price)]

[78, 78, 186, 172, 96, 92, 96, 60, 22, 114]