In [1]:
import numpy as np

In [2]:
price = np.array([2.6,7.2,6.92,3.88,0.78,2.67,8.87,0.23,5.23,6.3])

inventory = np.array([79,22,20,48,8,76,12,16,5,64])

product_value = price * inventory

product_value

array([205.4 , 158.4 , 138.4 , 186.24,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [7]:
product_value.sort()

product_value

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [4]:
reshaped_product_value = product_value.reshape(2,5)

reshaped_product_value

array([[205.4 , 158.4 , 138.4 , 186.24,   6.24],
       [202.92, 106.44,   3.68,  26.15, 403.2 ]])

In [5]:
np.median(reshaped_product_value)

148.4

In [8]:
np.percentile(reshaped_product_value, 50)

148.4

In [9]:
np.percentile(reshaped_product_value, 0)

3.68

In [10]:
np.percentile(reshaped_product_value, 100)

403.2

In [12]:
np.percentile(reshaped_product_value, 10)

5.984

In [13]:
np.sqrt(reshaped_product_value)

array([[ 1.91833261,  2.4979992 ,  5.11370707, 10.3169763 , 11.76435294],
       [12.58570618, 13.64697769, 14.24499912, 14.33178286, 20.07984064]])

In [15]:
# there are no duplicates in our array
np.unique(reshaped_product_value)

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [17]:
np.unique(np.ones(100))

array([1.])