In [1]:
import numpy as np

In [6]:
rng = np.random.default_rng(616)

price = (rng.random(10) * 10).round(2)
price

array([3.97, 8.66, 4.6 , 3.06, 5.74, 0.89, 8.82, 7.32, 7.32, 5.62])

In [7]:
inventory = rng.integers(0,100,10)

inventory

array([80, 33, 60,  6, 31, 35, 16, 20, 29, 43], dtype=int64)

In [9]:
price.mean()

5.6

In [10]:
inventory.mean()

35.3

In [11]:
inventory.sum()

353

In [13]:
inventory.max()

80

In [14]:
inventory.min()

6

In [15]:
inventory.std()

20.48438429633656

In [16]:
price.std()

2.407517393498955

In [17]:
(price * inventory)

array([317.6 , 285.78, 276.  ,  18.36, 177.94,  31.15, 141.12, 146.4 ,
       212.28, 241.66])

In [18]:
(price * inventory).sum()

1848.2900000000002

In [19]:
(price * inventory).mean()

184.829

In [20]:
(price * inventory).max()

317.6

In [21]:
(price * inventory).min()

18.36

In [22]:
(price * inventory).argmax()

0

In [23]:
(price * inventory).argmin()

3

In [24]:
price_2d = price.reshape(5,2)

In [25]:
price_2d

array([[3.97, 8.66],
       [4.6 , 3.06],
       [5.74, 0.89],
       [8.82, 7.32],
       [7.32, 5.62]])

In [26]:
price_2d.sum(axis=0)

array([30.45, 25.55])

In [27]:
price_2d.sum(axis=1)

array([12.63,  7.66,  6.63, 16.14, 12.94])

In [28]:
price_2d.mean(axis=1)

array([6.315, 3.83 , 3.315, 8.07 , 6.47 ])