In [1]:
import numpy as np

In [2]:
integer_array = np.arange(12)

In [3]:
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
integer_array[0]

0

In [6]:
integer_array[1]

1

In [7]:
integer_array[2]

2

In [8]:
integer_array[11]

11

In [9]:
integer_array[-1]

11

In [10]:
integer_array[-2]

10

In [11]:
integer_array[:5]

array([0, 1, 2, 3, 4])

In [12]:
integer_array[5:]

array([ 5,  6,  7,  8,  9, 10, 11])

In [13]:
integer_array[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
# step size of two
integer_array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [17]:
new_array = integer_array.reshape(3,4)

new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
new_array[ : , : ]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
new_array[1:, : ]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
new_array[ : ,3]

array([ 3,  7, 11])

In [25]:
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
new_array[ : ,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [27]:
new_array[ : ,1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [28]:
new_array[2,1]

9