In [1]:
import numpy as np

In [4]:
array = np.array(range(5))

In [5]:
array

array([0, 1, 2, 3, 4])

In [8]:
array_2d = np.array([range(5),range(5)])
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [12]:
array_2d = np.array([range(5),range(5)])
array_2d + 1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [13]:
array.shape

(5,)

In [14]:
array_2d.shape

(2, 5)

In [15]:
array.size

5

In [16]:
array_2d.size

10

In [17]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [18]:
array_2d.T.shape

(5, 2)

In [19]:
array.ndim

1

In [20]:
array_2d.ndim

2

In [21]:
array.dtype

dtype('int32')

In [22]:
array_2d.dtype

dtype('int32')

In [23]:
np.array(['I','Love','Python'])

array(['I', 'Love', 'Python'], dtype='<U6')