In [1]:
import numpy as np

In [2]:
product_value = np.array(
    [205.4, 158.4, 138.4, 186.24, 6.24, 202.92, 106.44, 3.68, 26.15, 403.2]
)

product_value

array([205.4 , 158.4 , 138.4 , 186.24,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [3]:
np.sort(product_value)

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [4]:
np.sort(product_value)[:5]

array([  3.68,   6.24,  26.15, 106.44, 138.4 ])

In [5]:
product_value.sort()

In [6]:
product_value

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [7]:
product_value[0]

3.68

In [8]:
product_value[-1]

403.2

In [9]:
product_value[::-1]

array([403.2 , 205.4 , 202.92, 186.24, 158.4 , 138.4 , 106.44,  26.15,
         6.24,   3.68])