In [1]:
import numpy as np

In [2]:
var = np.array([9,8,7,6])

print(var[1])

8


In [3]:
print(var[-3])

8


In [4]:
var1 = np.array([[1,2,3,4],[9,8,7,6]])

print(var1)

[[1 2 3 4]
 [9 8 7 6]]


In [6]:
print(var1.ndim)

2


In [10]:
#         row no.  index no.
print(var1[ 0    ,  2])

3


In [13]:
# three dimension
var2 = np.array([[[1,2],[6,7]]])

print(var2)
print(var2.ndim)

[[[1 2]
  [6 7]]]
3


In [14]:
print(var2[0,1,1])

7
