In [2]:
import numpy as np

var3 = np.array([9,8,7,6,1,2,3,4])
print(var3)

[9 8 7 6 1 2 3 4]


In [3]:
for i in np.nditer(var3):
    print(i)

9
8
7
6
1
2
3
4


In [4]:
# iterate in buffer
for i in np.nditer(var3, flags=['buffered'],op_dtypes=["S"]):
    print(i)

b'9'
b'8'
b'7'
b'6'
b'1'
b'2'
b'3'
b'4'


In [5]:
# iterate array with index numbers
for i , d in np.ndenumerate(var3):
    print(i,d)

(0,) 9
(1,) 8
(2,) 7
(3,) 6
(4,) 1
(5,) 2
(6,) 3
(7,) 4


In [7]:
var4 = np.array([[[1,2,3,4],[5,6,7,8],[4,3,2,1]]])
print(var4)
print()

for i, d in np.ndenumerate(var4):
    print(i,d)

[[[1 2 3 4]
  [5 6 7 8]
  [4 3 2 1]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
(0, 2, 0) 4
(0, 2, 1) 3
(0, 2, 2) 2
(0, 2, 3) 1
