In [1]:
import numpy as np

var = np.array([2,3,4,5,6])

print(var)

[2 3 4 5 6]


In [3]:
for i in var:
    print(i)

2
3
4
5
6


In [5]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)

[[1 2 3 4]
 [1 2 3 4]]


In [6]:
for j in var1:
    print(j)

[1 2 3 4]
[1 2 3 4]


In [8]:
for k in var1:
    for l in k:
        print(l)

1
2
3
4
1
2
3
4


In [9]:
var3 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)

[[[1 2 3 4]
  [1 2 3 4]]]


In [10]:
print(var3.ndim)

3


In [11]:
for i in var3:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
1
2
3
4
