In [1]:
import numpy as np

In [2]:
var = np.array([1,2,3,4,5,6,7])

print(var)

[1 2 3 4 5 6 7]


In [3]:
print("2 to 5 : ", var[1:5])

2 to 5 :  [2 3 4 5]


In [4]:
print("2 to End : ", var[1:])

2 to End :  [2 3 4 5 6 7]


In [9]:
var = np.array([9,8,7,6,3,2,1])

print(var)

[9 8 7 6 3 2 1]


In [8]:
print("start to 5 : ", var[:5])

start to 5 :  [9 8 7 6 3]


In [10]:
print("stop : ", var[::2])

stop :  [9 7 3 1]


In [12]:
print("steps : ", var[:4:2])

steps :  [9 7]


In [13]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])

print(var1)

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]


In [14]:
print(var1.ndim)

2


In [16]:
print(" 8 to 5 : ", var1[1,1:])

 8 to 5 :  [8 7 6 5]


In [17]:
print(var1[2,1:])

[12 13 14 15]
