In [2]:
# import the library
import numpy as np

In [3]:
lst = [1,2,3,4]

In [4]:
lst

[1, 2, 3, 4]

In [5]:
type(lst)

list

One Dimensional Array

In [6]:
arr = np.array(lst)

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.shape

(4,)

Two Dimensional Array

In [10]:
list1 = [1,2,3,4]
list2 = [2,3,4,5]
list3 = [3,4,5,6]

In [11]:
arr1 = np.array([list1, list2, list3])

In [12]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [13]:
type(arr1)

numpy.ndarray

In [14]:
arr1.shape

(3, 4)

Indexing One Dimensional

In [15]:
arr

array([1, 2, 3, 4])

In [16]:
arr[1:]

array([2, 3, 4])

In [17]:
arr[2:]

array([3, 4])

In [18]:
arr[1:3]

array([2, 3])

In [19]:
arr

array([1, 2, 3, 4])

In [20]:
arr[-1]

4

In [21]:
arr[:-1]

array([1, 2, 3])

In [22]:
arr[::-1]

array([4, 3, 2, 1])

In [23]:
arr[::]

array([1, 2, 3, 4])

In [24]:
arr[::-2]

array([4, 2])

In [25]:
arr[::-3]

array([4, 1])

Indexing Two Dimensional

In [26]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [27]:
arr1[:,1]

array([2, 3, 4])

In [28]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [29]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [30]:
arr1[2:,1:3]

array([[4, 5]])

In [31]:
arr1[1:,2:]

array([[4, 5],
       [5, 6]])

In [33]:
arr1[:,2:]

array([[3, 4],
       [4, 5],
       [5, 6]])

In [34]:
arr1[:,2:].shape

(3, 2)

In [35]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [42]:
arr1[:,::3]

array([[1, 4],
       [2, 5],
       [3, 6]])

EDA- Exploratory Data Analysis

In [43]:
arr

array([1, 2, 3, 4])

In [44]:
arr<2

array([ True, False, False, False])

In [45]:
arr[arr<2]

array([1])

In [46]:
arr[arr<3]

array([1, 2])

Reshaping

In [47]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [48]:
arr1.reshape(4,3)

array([[1, 2, 3],
       [4, 2, 3],
       [4, 5, 3],
       [4, 5, 6]])

In [49]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [50]:
arr1.reshape(4,3)

array([[1, 2, 3],
       [4, 2, 3],
       [4, 5, 3],
       [4, 5, 6]])