### Package Imports

In [1]:
import numpy as np

# Assignment 1: Array Basics

Hi there,

Can you import Numpy and convert the following list comprehension (I just learned about comprehensions in an awesome course by Maven) into an array?

Once you've done that report the following about the array:
* The number of dimensions 
* The shape
* The number of elements in the array
* The type of data contained inside

In [2]:
my_list = [x * 10 for x in range(1, 11)]

In [3]:
my_list

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [4]:
my_list = np.array(my_list)

In [5]:
my_list

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [6]:
print(my_list.ndim)
print(my_list.shape)
print(my_list.size)
print(my_list.dtype)

1
(10,)
10
int32


# Assignment 2: Array Creation

Thanks for your help with the first piece - I'm starting to understand some of the key differences between base Python data types and NumPy arrays. 

Does NumPy have anything like the range() function from base Python?

If so: 
* create the same array from assignment 1 using a NumPy function. 
* Make it 5 rows and 2 columns. 
* It's ok if the datatype is float or int.

In [7]:
array_ = np.arange(1,50,5).reshape(5,2)
array_

array([[ 1,  6],
       [11, 16],
       [21, 26],
       [31, 36],
       [41, 46]])

Looking good so far! One of our data scientists asked about random number generation in NumPy.

Can you create a 3x3 array of random numbers between 0 and 1? Use a random state of 2022.

Store the random array in a variable called `random_array`.

In [8]:
random_array = np.random.default_rng(2022)

random_array.integers(0,10,9).reshape(3,3)

array([[7, 2, 7],
       [0, 1, 6],
       [9, 0, 0]], dtype=int64)

# Assignment 3: Accessing Array Data


Slice and index the `random_array` we created in the previous exercise. Perform the following:

* Grab the first two 'rows' of the array
* Grab the entire first column
* Finally, grab the second element of the third row.

Thanks!


In [9]:
random_array

Generator(PCG64) at 0x20678CCBA00

In [10]:
random_array = np.random.default_rng(2022)
random_numbers = random_array.integers(0, 10, 9).reshape(3, 3)
result = random_numbers[:2, :]

print(result)


[[7 2 7]
 [0 1 6]]


In [11]:
random_numbers

array([[7, 2, 7],
       [0, 1, 6],
       [9, 0, 0]], dtype=int64)

In [12]:
result = random_numbers[:,0]
print(result)

[7 0 9]


In [13]:
result = random_numbers[:,:1]
print(result)

[[7]
 [0]
 [9]]


In [14]:
result = random_numbers[2,1]
print(result)

0


# Assignment 4: Arithmetic Operations

The creativity of our marketing team knows no bounds!

They've asked us to come up with a simple algorithm to provide a random discount to our list of prices below. 

Before we do that, 

* Add a 5 dollar shipping fee to each price. Call this array `total`.

Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from `random_array`, reshape it to one dimension. Call this `discount_pct`.
* Subtract `discount_pct` FROM 1, store this in `pct_owed`.
* Multiply `pct_owed` by `total` to get the final amount owed.

In [15]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])


In [16]:
random_numbers

array([[7, 2, 7],
       [0, 1, 6],
       [9, 0, 0]], dtype=int64)

In [17]:
random_numbers[:2]

array([[7, 2, 7],
       [0, 1, 6]], dtype=int64)

In [18]:
discount_pct = random_numbers[:2,:].reshape(6)
discount_pct

array([7, 2, 7, 0, 1, 6], dtype=int64)

In [19]:
pct_owed = 1 - discount_pct
pct_owed

array([-6, -1, -6,  1,  0, -5], dtype=int64)

In [20]:
total = prices + 5

In [21]:
Stotal = total * pct_owed
Stotal

array([ -65.94,  -11.99, -164.94,  104.99,    0.  , -274.95])

In [22]:
((1-(random_numbers[:2,:].reshape(6))) * total).round(2)

array([ -65.94,  -11.99, -164.94,  104.99,    0.  , -274.95])

# Assignment 5: Filtering Arrays

Filter the product array to only include those with prices greater than 25.

Modify your logic to include cola, despite it not having a price greater than 25. 
Store the elements returned in an array called `fancy_feast_special`.

Next, create a shipping cost array where the cost is 0 if price is greater than 20, and 5 if not. 

In [23]:
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)

products

array(['salad', 'bread', 'mustard', 'rare tomato', 'cola',
       'gourmet ice cream'], dtype='<U17')

In [24]:
prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [25]:
products[prices > 25]

array(['rare tomato', 'gourmet ice cream'], dtype='<U17')

In [26]:
mask = (prices > 25) | (products == 'cola')
fancy_feast_special = products[mask]
fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [27]:
shipping_cost = np.where(prices > 20,0,5)
shipping_cost

array([5, 5, 0, 0, 5, 0])

# Assignment 6: Aggregating and Sorting Arrays

First, grab the top 3 highest priced items in our list. 

Then, calculated the mean, min, max, and median of the top three prices.

Finally, calculate the number of unique price tiers in our `price_tiers` array.

In [28]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [29]:
prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [30]:
top3 = prices[-3:]

In [31]:
top3.mean()

51.656666666666666

In [32]:
top3.mean()

51.656666666666666

In [33]:
top3.max()

99.99

In [34]:
np.median(top3)

49.99

In [35]:
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])

In [36]:
np.unique(price_tiers)

array(['budget', 'luxury', 'mid-tier'], dtype='<U8')

# Assignment 7: Bringing it All Together

Ok, final NumPy task - let's read in some data with the help of Pandas.

Our data scientist provided the code to read in a csv as a Pandas dataframe, and has converted the two columns of interest to arrays.

* Filter `sales_array` down to only sales where the product family was produce. 

* Then, randomly sample roughly half (random number < .5) of the produce sales and report the mean and median sales. Use a random seed of 2022.

* Finally, create a new array that has the values 'above_both', 'above_median', and 'below_both' based on whether the sales were above the median and mean of the sample, just above the median of the sample, or below both the median and mean of the sample. 

In [37]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv(
    "../retail/retail_2016_2017.csv", skiprows=range(1, 11000), nrows=1000
)

family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])

In [41]:
retail_df.head()

id        date  store_nbr        family    sales  onpromotion
0  1956943  2016-01-07         18          EGGS   177.00            0
1  1956944  2016-01-07         18  FROZEN FOODS    36.00            0
2  1956945  2016-01-07         18     GROCERY I  2291.06            6
3  1956946  2016-01-07         18    GROCERY II    16.00            0
4  1956947  2016-01-07         18      HARDWARE     2.00            0

In [45]:
produce_sales = sales_array[family_array == "PRODUCE"]

In [48]:
rng = np.random.default_rng(20202)

random_array = rng.random(30)
random_array

array([0.35988124, 0.63903158, 0.88570028, 0.51497374, 0.49405231,
       0.25302602, 0.63382338, 0.56732986, 0.70162267, 0.72850184,
       0.16104483, 0.63579484, 0.83955472, 0.08197943, 0.48506892,
       0.22138481, 0.62101517, 0.20444564, 0.21626593, 0.39174548,
       0.44558827, 0.61019611, 0.01929296, 0.88697265, 0.24146718,
       0.0255946 , 0.81760247, 0.65207336, 0.19942893, 0.82656156])

In [51]:
sampled_array = produce_sales[random_array < 0.5]

In [55]:
mean = sampled_array.mean()
mean

1542.7617999999995

In [56]:
median = np.median(sampled_array)
median

1155.385

In [57]:
np.where(
    sampled_array < median,
    "below_both",
    np.where(sampled_array > mean, "above_both", "above_median")

)

array(['above_both', 'above_median', 'below_both', 'above_both',
       'above_both', 'below_both', 'above_median', 'below_both',
       'below_both', 'below_both', 'above_median', 'above_both',
       'above_both', 'below_both', 'below_both'], dtype='<U12')

In [58]:
sampled_array

array([1662.394, 1236.404,  298.441, 1852.786, 7860.031,  446.038,
       1155.385,  862.092,  473.952,  254.263, 1272.755, 2030.762,
       2339.906,  722.333,  673.885])